extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:promise/recommended
  - standard
parserOptions:
  ecmaVersion: 2015
rules:
  import/newline-after-import: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "*"
        - ".*"
  import/order:
    - error
    - groups:
        - builtin
        - [external, internal]
        - [parent, sibling, index]
        - unknown
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
overrides:
  - files: "*.js"
    extends:
      - plugin:dprint/recommended
    rules:
      dprint/dprint:
        - error
        - config: &dprint-config
            indentWidth: 2
            quoteStyle: preferSingle
            singleBodyPosition: sameLine
            typeParameters.trailingCommas: never
            arrowFunction.useParentheses: preferNone
            constructorType.spaceAfterNewKeyword: true
            taggedTemplate.spaceBeforeLiteral: false
            typeAssertion.spaceBeforeExpression: false
  - files: rollup.config.js
    parserOptions:
      ecmaVersion: 2021
      sourceType: module
  - files: "*.ts"
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:import/typescript
      - standard-with-typescript
      - plugin:dprint/recommended
    parserOptions:
      sourceType: module
      project:
        - ./tsconfig.json
        - ./types.node_modules/tsconfig.json
    rules:
      dprint/dprint:
        - error
        - config:
            <<: *dprint-config
            indentWidth: 4
      # I don't want to use "nodeify" package.
      promise/no-callback-in-promise: off
      # The "@typescript-eslint/strict-boolean-expressions" rule is very strict and stressful.
      "@typescript-eslint/strict-boolean-expressions": off
  - files: "*.d.ts"
    rules:
      # The "no-redeclare" rule does not support namespace and function declarations of the same name.
      # example:
      #   declare function foo(): void;
      #   declare namespace foo { ... } // ESLint: error 'foo' is already defined
      # In addition, as of 2020/06/11, there is no alternative to the "no-redeclare" rule in "@typescript-eslint"
      no-redeclare: off
      # The "@ts-expect-error" comment is not allowed in TypeScript 3.8 or earlier.
      # If someone forks a type definition created in this project, the type definition will not be available in older versions of TypeScript.
      "@typescript-eslint/prefer-ts-expect-error": off
